Repository UB-ES-2018/picturest, pull requests merged in 2018-11, with the labels that each got.

#40 Us 08 backend to Sprint_3
  server/controllers/user.js
  server/models/user.js
  server/routes/user.js
Labels: backend, enhancement, sprint_3

#41 US-09-Backend done, to test
  server/controllers/image.js
  server/controllers/user.js
  server/models/user.js
  server/routes/user.js
Labels: backend, enhancement, sprint_3

#42 Pin Image
  server/controllers/user.js
  server/routes/user.js
  static/Perfil.html
  static/js/examples.js
Labels: frontend, sprint_3

#44 Corregidos Errores de SignIn y SignUp
  static/js/examples.js
  static/signin.html
  static/signup.html
Labels: bug, frontend, sprint_3

#58 Sprint4 fix to Sprint4
  server/controllers/image.js
  static/Perfil.html
  static/js/examples.js
  static/signin.html
  static/signup.html
Labels: bug, frontend, sprint_4

#66 Us 06 frontend
  static/Images/No-Profile.png
  static/js/examples.js
  static/settings.html
Labels: frontend, sprint_4
